[imageflux]
token = ""
encrypt-key-uri = ""
event_webhook_url=""

# 1080p
[[ imageflux.hls ]]
duration-seconds = 1
start-time-offset = -2

[ imageflux.hls.video ]
width = 1920
height = 1080
fps = 60
bps = 15000000

[ imageflux.hls.audio ]
bps = 320000

[ imageflux.hls.archive ]
archive_destination_id=""

# 720p
[[ imageflux.hls ]]
duration-seconds = 1
start-time-offset = -2

[ imageflux.hls.video ]
width = 1280
height = 720
fps = 60
bps = 2500000

[ imageflux.hls.audio ]
bps = 128000

[ imageflux.hls.archive ]
archive_destination_id=""

# 480p
[[ imageflux.hls ]]
duration-seconds = 1
start-time-offset = -2

[ imageflux.hls.video ]
width = 854
height = 480
fps = 24
bps = 950000

[ imageflux.hls.audio ]
bps = 96000

[ imageflux.hls.archive ]
archive_destination_id=""

[cloudflare]
token = ""
kv-account-id = ""
kv-namespace-id = ""

[patlite]
IP = "192.168.10.1"